# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - src_tuesday/1

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: 'sc_hms_terraform'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az login
      az account list
      az account set --subscription="99c19e8a-0929-4a39-af63-a232d1686654"
      
      terraform init
      terraform plan
      terraform apply -auto-approve

      sleep 30
      
      terraform destroy -auto-approve
    addSpnToEnvironment: true
    workingDirectory: 'src_tuesday/1/'